"""TC-19-1 (NFR-6) — coverage threshold."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

pytestmark = pytest.mark.required

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output"
THRESHOLD = 0.90


def _coverage_reports() -> list[Path]:
    """Return every coverage XML report present in ``output/``.

    ``nox -s test`` writes one report per interpreter (``coverage.3.12.xml``);
    the pipeline's ``coverage`` job writes the combined ``coverage.xml``. Both
    are accepted so this check verifies whatever the job it runs in produced,
    rather than skipping whenever the combined report happens to be absent.
    """
    combined = OUTPUT_DIR / "coverage.xml"
    if combined.is_file():
        return [combined]
    return sorted(OUTPUT_DIR.glob("coverage.*.xml"))


def _line_rate(report: Path) -> float:
    root = ET.parse(report).getroot()  # noqa: S314 — locally generated by nox -s test
    return float(root.attrib["line-rate"])


@pytest.mark.test_case("19-1")
class TestCoverageThreshold:
    def test_coverage_xml_exists(self) -> None:
        reports = _coverage_reports()
        if not reports:
            pytest.skip(f"no coverage report in {OUTPUT_DIR} — run `nox -s test` first")
        assert all(r.is_file() for r in reports)

    def test_line_rate_meets_threshold(self) -> None:
        reports = _coverage_reports()
        if not reports:
            pytest.skip(f"no coverage report in {OUTPUT_DIR} — run `nox -s test` first")
        below = {r.name: rate for r in reports if (rate := _line_rate(r)) < THRESHOLD}
        assert not below, "line coverage below {:.0%} threshold: {}".format(
            THRESHOLD,
            ", ".join(f"{name} at {rate:.2%}" for name, rate in sorted(below.items())),
        )
