"""TC-19-1 (NFR-6) — coverage threshold."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

COVERAGE_XML = Path(__file__).resolve().parents[2] / "output" / "coverage.xml"
THRESHOLD = 0.90


@pytest.mark.test_case("19-1")
class TestCoverageThreshold:
    def test_coverage_xml_exists(self) -> None:
        if not COVERAGE_XML.exists():
            pytest.skip(f"{COVERAGE_XML} not present — run `nox -s test` first")
        assert COVERAGE_XML.is_file()

    def test_line_rate_meets_threshold(self) -> None:
        if not COVERAGE_XML.exists():
            pytest.skip(f"{COVERAGE_XML} not present — run `nox -s test` first")
        root = ET.parse(COVERAGE_XML).getroot()  # noqa: S314 — locally generated by nox -s test
        line_rate = float(root.attrib["line-rate"])
        assert line_rate >= THRESHOLD, f"line coverage {line_rate:.2%} below {THRESHOLD:.0%} threshold"
