"""DataEval Workflows - Data evaluation and monitoring pipelines.

Quick start::

    from pathlib import Path
    from dataeval_flow import load_config, run_tasks

    config = load_config(Path("/path/to/data/config.yaml"))  # a file, or a folder of them
    results = run_tasks(config, data_dir=Path("/path/to/data"))  # keyed by task name
    for name, result in results.items():
        print(result.report())  # text report
        result.export(f"output/{name}.json")  # write result JSON

Or run one workflow or evaluator on a dataset already in memory, typed to its result::

    from dataeval_flow import run
    from dataeval_flow.evaluators.quality import DuplicatesConfig

    result = run(DuplicatesConfig(), dataset)  # a DuplicatesResult
    print(result.report())

Or build a pipeline programmatically::

    from dataeval_flow import PipelineConfig, run_tasks
    from dataeval_flow.config import HuggingFaceDatasetConfig, SourceConfig, TaskConfig
    from dataeval_flow.config.extractors import FlattenExtractorConfig
    from dataeval_flow.workflows.data_cleaning import DataCleaningConfig

Discovery helpers live with each kind, and list every installed type, plugins included::

    >>> from dataeval_flow.workflows import list_workflows
    >>> [cls.name for cls in list_workflows()]
    ['data-analysis', 'data-cleaning', ...]

    >>> from dataeval_flow.evaluators import list_evaluators
    >>> [cls.name for cls in list_evaluators()]
    ['quality.duplicates', 'quality.outliers']
"""

from dataeval_flow._dataset import load_dataset
from dataeval_flow._input_spec import InputKind, InputSpec, SourceCount
from dataeval_flow._orchestrator import run_task, run_tasks
from dataeval_flow._result import Result, ResultMetadata
from dataeval_flow._run import run
from dataeval_flow.config._loader import load_config
from dataeval_flow.config._models import PipelineConfig

__all__ = [
    "load_config",
    "load_dataset",
    "run",
    "run_task",
    "run_tasks",
    "PipelineConfig",
    "Result",
    "ResultMetadata",
    "InputSpec",
    "InputKind",
    "SourceCount",
    "__version__",
]

try:
    from dataeval_flow._version import __version__
except ImportError:  # pragma: no cover
    # _version.py is generated by the hatch-vcs build hook and is not tracked in
    # git. When importing from a source tree whose build hook did not run (e.g. a
    # cached editable install), fall back to the installed distribution metadata.
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as _dist_version

    try:
        __version__ = _dist_version("dataeval-flow")
    except PackageNotFoundError:
        __version__ = "unknown"

# Strongly type for pyright
__version__ = str(__version__)

import logging

# Library-style default: attach a NullHandler so importing dataeval_flow without
# running the CLI (which calls setup_logging) never emits unconfigured output or
# triggers the logging "last resort" handler. The CLI configures real handlers on
# the root logger via dataeval_flow._logging.setup_logging.
logging.getLogger(__name__).addHandler(logging.NullHandler())
